-- CDR_BUILDING.BLDGAPPL

SELECT COUNT(*) "COUNT", YEAR(MODDTTM) "YEAR", MONTH(MODDTTM) "MONTH"
FROM CDR_BUILDING.BLDGAPPL GROUP BY YEAR(MODDTTM), MONTH(MODDTTM)
HAVING YEAR(MODDTTM) IS NOT NULL
ORDER BY YEAR(MODDTTM)


SELECT COUNT(*) "COUNT", YEAR(MODDTTM) "YEAR", MONTH(MODDTTM) "MONTH"
FROM CDR_BUILDING.BLDGAPPL GROUP BY YEAR(MODDTTM), MONTH(MODDTTM)
HAVING YEAR(MODDTTM) IS NOT NULL
ORDER BY YEAR(MODDTTM)



-- CDR_BUILDING.BLDGREVIEW

SELECT COUNT(*) "COUNT", YEAR(MODDTTM) "YEAR", MONTH(MODDTTM) "MONTH"
FROM CDR_BUILDING.BLDGREVIEW GROUP BY YEAR(MODDTTM), MONTH(MODDTTM)
HAVING YEAR(MODDTTM) IS NOT NULL
ORDER BY YEAR(MODDTTM)


SELECT COUNT(*) "COUNT", YEAR(MODDTTM) "YEAR", MONTH(MODDTTM) "MONTH"
FROM CDR_BUILDING.BLDGAPPL GROUP BY YEAR(MODDTTM), MONTH(MODDTTM)
HAVING YEAR(MODDTTM) IS NOT NULL
ORDER BY YEAR(MODDTTM)


--CDR_BUILDING.BLDGINSP

SELECT COUNT(*) "COUNT", YEAR(MODDTTM) "YEAR", MONTH(MODDTTM) "MONTH"
FROM CDR_BUILDING.BLDGINSP GROUP BY YEAR(MODDTTM), MONTH(MODDTTM)
HAVING YEAR(MODDTTM) IS NOT NULL
ORDER BY YEAR(MODDTTM)


SELECT COUNT(*) "COUNT", YEAR(MODDTTM) "YEAR", MONTH(MODDTTM) "MONTH"
FROM CDR_BUILDING.BLDGINSP GROUP BY YEAR(MODDTTM), MONTH(MODDTTM)
HAVING YEAR(MODDTTM) IS NULL
ORDER BY YEAR(MODDTTM)


-- CDR_PLANNING.PLANAPPL
SELECT COUNT(*) "COUNT", YEAR(MODDTTM) "YEAR", MONTH(MODDTTM) "MONTH"
FROM CDR_PLANNING.PLANAPPL GROUP BY YEAR(MODDTTM), MONTH(MODDTTM)
HAVING YEAR(MODDTTM) IS NOT NULL
ORDER BY YEAR(MODDTTM)


SELECT COUNT(*) "COUNT", YEAR(MODDTTM) "YEAR", MONTH(MODDTTM) "MONTH"
FROM CDR_PLANNING.PLANAPPL GROUP BY YEAR(MODDTTM), MONTH(MODDTTM)
HAVING YEAR(MODDTTM) IS NOT NULL
ORDER BY YEAR(MODDTTM)




SELECT
CAST(CDR_PLANNING.PLANREVIEW."APPLANKEY" AS VARCHAR) + '_PLANREVIEW' AS "ID",
CDR_PLANNING.PLANREVIEW."COMMENTS",
CDR_PLANNING.PLANREVIEW."COMMENTS_SEARCH",
CDR_PLANNING.PLANREVIEW."MODDTTM",
CDR_PLANNING.PLANREVIEW."ADDDTTM",
'PLANREVIEW' AS "TYPE"
FROM CDR_PLANNING.PLANREVIEW


UNION ALL

SELECT
CAST(CDR_PLANNING.PLANINSP."APPLANINSPKEY" AS VARCHAR) + '_PLANINSP' AS "ID",
CDR_PLANNING.PLANINSP."COMMENTS",
CDR_PLANNING.PLANINSP."COMMENTS_SEARCH",
CDR_PLANNING.PLANINSP."MODDTTM",
CDR_PLANNING.PLANINSP."ADDDTTM",
'PLANINSP' AS "TYPE"
FROM CDR_PLANNING.PLANINSP


UNION ALL

SELECT
CAST(CDR_PROJECT.PROJAPPL."APPROJKEY" AS VARCHAR) + '_PROJAPPL' AS "ID",
CDR_PROJECT.PROJAPPL."COMMENTS",
CDR_PROJECT.PROJAPPL."COMMENTS_SEARCH",
CDR_PROJECT.PROJAPPL."MODDTTM",
CDR_PROJECT.PROJAPPL."ADDDTTM",
'PROJAPPL' AS "TYPE"
FROM CDR_PROJECT.PROJAPPL


UNION ALL

SELECT
CAST(CDR_PROJECT.PROJREVIEW."APPROJREVIEWKEY" AS VARCHAR) + '_PROJREVIEW' AS "ID",
CDR_PROJECT.PROJREVIEW."COMMENTS",
CDR_PROJECT.PROJREVIEW."COMMENTS_SEARCH",
CDR_PROJECT.PROJREVIEW."MODDTTM",
CDR_PROJECT.PROJREVIEW."ADDDTTM",
'PROJREVIEW' AS "TYPE"
FROM CDR_PROJECT.PROJREVIEW


UNION ALL

SELECT
CAST(CDR_PROJECT.PROJINSP."APPROJINSPKEY" AS VARCHAR) + '_PROJINSP' AS "ID",
CDR_PROJECT.PROJINSP."COMMENTS",
CDR_PROJECT.PROJINSP."COMMENTS_SEARCH",
CDR_PROJECT.PROJINSP."MODDTTM",
CDR_PROJECT.PROJINSP."ADDDTTM",
'PROJINSP' AS "TYPE"
FROM CDR_PROJECT.PROJINSP


UNION ALL

SELECT
CAST(BILLING.ACCOUNTALERT."ACCOUNTALERTKEY" AS VARCHAR) + '_ACCOUNTALERT' AS "ID",
BILLING.ACCOUNTALERT."COMMENTS",
BILLING.ACCOUNTALERT."COMMENTS_SEARCH",
BILLING.ACCOUNTALERT."MODDTTM",
BILLING.ACCOUNTALERT."ADDDTTM",
'ACCOUNTALERT' AS "TYPE"
FROM BILLING.ACCOUNTALERT


UNION ALL

SELECT
CAST(CRM.CUSTCALL."CSTCALKEY" AS VARCHAR) + '_CUSTCALL' AS "ID",
CRM.CUSTCALL."COMMENTS",
CRM.CUSTCALL."COMMENTS_SEARCH",
CRM.CUSTCALL."MODDTTM",
CRM.CUSTCALL."ADDDTTM",
'CUSTCALL' AS "TYPE"
FROM CRM.CUSTCALL
